@startuml
participant "Main Function"
participant calucate
participant getInput

activate "Main Function"
"Main Function" -> calucate: 計算を実行
activate calucate
calucate -> getInput: 入力を取得
activate getInput
getInput --> calucate: 入力データ
deactivate getInput
calucate --> "Main Function": 計算結果
deactivate calucate
@enduml